export const GROWTH_CONFIG = {
  MAX_PRICE_MULTIPLIER: 1.40, // Target price <= source price * 1.40 for valid upsells
  UPSELL_WEIGHTS: {
    FEATURE_IMPROVEMENT: 40,
    RATING_IMPROVEMENT: 20,
    PRICE_REASONABLENESS: 20,
    RELATIONSHIP_PRIORITY: 15,
    STOCK: 5,
  },
  CROSS_SELL_WEIGHTS: {
    RELATIONSHIP_PRIORITY: 40,
    RATING_QUALITY: 30,
    PRICE_REASONABLENESS: 20,
    STOCK: 10,
  },
  LIMITS: {
    DEFAULT_UPSELLS: 2,
    DEFAULT_CROSS_SELLS: 2,
    MAX_SUGGESTIONS: 3,
  },
} as const;
